### ISSUE TITLE
Failed to create machine due to bad file descriptor

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-core#105]
During deployment of an s3 I saw this error passing by in the dm robot

![image](https://user-images.githubusercontent.com/23582741/50274275-1dbdb980-043d-11e9-8fd0-bae2ff88a070.png)

**Comment by muhamadazmy** [comment]
It's probably because failure to download the file. @maxux already linked a 0-fs issue where we will discuss how to handle corrupt downloads

**Comment by muhamadazmy** [comment]
Some improvement has been added to validate the file while downloading. There is still no fallback in case file got corrupted later after the download! 

Anyway, a bad file descriptor error is probably failure to download, and can be due to networking glitch. The caller need to try again when it gets such error.
