### ISSUE TITLE
0-fs can't reach the hub.grif.tf:9900 if a port forward for port 9900 exist on the node

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#56]
let me explain the setup:
zos on bare metal -> zos VM -> 0-robot container
this is the nft ruleset of the zero on bare metal:
```
table ip nat {
	chain pre {
		type nat hook prerouting priority 0; policy accept;
		iif != "core0" iifname "zt*" tcp dport 6600 dnat to 172.18.0.2:6600
		iif != "core0" tcp dport 9902 dnat to 172.18.0.6:9900
		iif != "core0" tcp dport 9910 dnat to 172.18.0.3:9900
		iif != "core0" tcp dport 9909 dnat to 172.18.0.9:9900
		iif != "core0" tcp dport 9907 dnat to 172.18.0.4:9900
		iif != "core0" tcp dport 9906 dnat to 172.18.0.10:9900
		iif != "core0" tcp dport 9904 dnat to 172.18.0.5:9900
		iif != "core0" tcp dport 9908 dnat to 172.18.0.7:9900
		iif != "core0" tcp dport 9901 dnat to 172.18.0.8:9900
		iif != "core0" tcp dport 9903 dnat to 172.18.0.11:9900
		iif != "core0" tcp dport 9900 dnat to 172.18.0.12:9900
	}

	chain post {
		type nat hook postrouting priority 0; policy accept;
		ip saddr 172.18.0.0/16 masquerade
		ip saddr 172.19.0.0/16 masquerade
	}
}
table inet filter {
	chain pre {
		type filter hook prerouting priority 0; policy accept;
	}

	chain forward {
		type filter hook forward priority 0; policy accept;
	}

	chain output {
		type filter hook output priority 0; policy accept;
	}

	chain input {
		type filter hook input priority 0; policy drop;
		ct state { established, related } accept
		iifname "lo" accept
		iifname "vxbackend" accept
		ip protocol 1 accept
		iif "core0" udp dport { domain, bootps, bootpc } accept
		iifname "zt*" tcp dport 6379 accept
		iif "kvm0" udp dport { domain, bootps, bootpc } accept
	}
}
```

the problem is that in the container, 0-fs tries to access `hub.grid.tf:9900`
but because of the nft rule, 9900 is forwarder to a local zerodb that we happen to also have listening on that port 9900 on the local machine which makes everything fails since of course the file we are looking for are not in the local zerodb.

**Comment by muhamadazmy** [comment]
I have to clarify that it's the 0-fs on the guest ZOS that has this issue, 0-fs on the host (for host containers) or even the guest vm are working fine

**Comment by zaibon** [comment]
> I have to clarify that it's the 0-fs on the guest ZOS that has this issue, 0-fs on the host (for host containers) or even the guest vm are working fine

indeed

**Comment by muhamadazmy** [comment]
More input from the latest issues we faced

## Setup

```
---------------
    Minio    |
      vm     |
--------------
     | vm bridge 
-------------------------------------------------------
- containers-bridge
  - 9901:ZDB0
  - 9902:ZDB1
  - 9903:ZDB2
  - ...
--------------------------------------------------------
```

- We have a Minio ZOS vm running on top of host ZOS vm. The host vm also hosts local zdb with "proper" port forwards.
- The rules applies to all traffic that is intended to dest port 9901, 9902, etc as shown in the graph, except for traffic coming from the container bridge. 
- Main problem happens is that a traffice that is NOT directed to host zos node (traffic that should be routed instead) also gets redirected to the zdb. for example if the any of VMs (minio zos in this case) is trying to reach out for hub.grid.tf:9901 it will be redirected to the locally hosted zdb instead!

Problem is that the port forward rule should be explicit to only redirect traffic that is intended to the host itself (like an input traffic), the problem is we don't know all the host ips and we can't change that dynamically

One suggestion is to use OpenVSwitch to do so, but that's require a rewrite for a huge part of zos networking and can't be done fast enough (I am still not sure if this can fix our problem in the first place) 

Another faster solution is to only enable port forward for traffic that is intended to the IP of the eth0, the bond backend interface, and the main zt ip.

**Comment by zaibon** [comment]
This issue is also blocking when deploying minio. Cause since we can have zerodb running on every node, when minio is trying to reach a zerodb on a another node but that port of zerodb is also forwarded on the local node, the same bug appears.

**Comment by zaibon** [comment]
fixed by: https://github.com/threefoldtech/0-core/commit/d7e76cd5b488fa2f8cf7cc3f0b98334d096fb37d
